# Generated by Django 4.2.4 on 2023-08-10 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='disease',
            old_name='Sym',
            new_name='symptoms',
        ),
    ]
