# Generated by Django 4.2.4 on 2023-08-10 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_disease_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='disease',
            name='description',
            field=models.CharField(default=' ', max_length=100),
        ),
    ]
