# Generated by Django 4.2.4 on 2023-08-10 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_disease_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disease',
            name='slug',
        ),
        migrations.AddField(
            model_name='symptom',
            name='description',
            field=models.TextField(default=' '),
        ),
        migrations.AlterField(
            model_name='disease',
            name='description',
            field=models.TextField(default=' '),
        ),
    ]
